apps/home/urls.py
from django.urls import path, re_path
from apps.home import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [

    path('', views.index, name='home'),

    path('create-project', views.create_new_project, name='create_project'),

    path('category_form', views.add_category, name='create_category'),

    path('project-details/<int:project_id>', views.show_project_details, name='show_project'),

    path('project-details/<int:project_id>/donate', views.donate, name='donate'),

    path('project-details/<int:project_id>/comment', views.create_comment, name='create_comment'),

    path('project-details/<int:project_id>/cancel', views.cancel_project, name='cancel_project'),

    path('project-details/<int:project_id>/report', views.add_report, name='create_report'),

    path('project-details/<int:comment_id>/report_comment', views.add_comment_report, name='create_comment_report'),

    path('project-details/<int:comment_id>/reply', views.create_comment_reply, name='create_comment_reply'),

    path('projects', views.all_projects, name='all_projects'),

    path('projects/category/<int:category_id>', views.get_category_projects, name='get_category'),

    path('projects/tag/<int:tag_id>', views.get_tag_projects, name='get_tag'),

    path('projects/featured', views.get_featured_projects, name='featured_projects'),

    path('search-result', views.search, name='search-result'),

    path('<int:project_id>/rate', views.rate, name='project_rate'),

    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this
from django.conf.urls.static import static
from django.conf import settings




urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls"))             # UI Kits Html files
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/models.py
from django.utils import timezone
from django.db import models

from django.db import models
from pkg_resources import require
from apps.authentication.models import Register
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=250)
    
    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100,null=True, blank=True)

    def __str__(self):
        return self.name


class Project(models.Model):
    title = models.CharField(max_length=100)
    details = models.TextField()
    total_target = models.FloatField()
    start_time = models.DateTimeField(default=timezone.now)
    end_time = models.DateTimeField(default=timezone.now)
    is_featured = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    user = models.ForeignKey(Register, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
   

    def __str__(self):
        return self.title
    

class Image(models.Model):
    images = models.ImageField(upload_to="")
    project = models.ForeignKey(Project, on_delete=models.CASCADE, default=None)


class Comment(models.Model):
    comment = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(Register, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(f'comment by {self.user.first_name} on {self.project.title} project.')


class Donation(models.Model):
    donation = models.FloatField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(Register, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    

class Project_Report(models.Model):
    REPOT_DATA=[('ip','inappropriate'),('ags','aggressive')]
    report =  models.CharField(
        max_length=200,
        choices=REPOT_DATA,
        default='ip',
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(Register, on_delete=models.CASCADE)


class Comment_Report(models.Model):
    REPOT_DATA=[('ip','inappropriate')]
    report =  models.CharField(
        max_length=200,
        choices=REPOT_DATA,
        default='ip',
    )
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(Register, on_delete=models.CASCADE)


class Reply(models.Model):
    reply = models.CharField(max_length=30)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    user = models.ForeignKey(Register, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


class Rate(models.Model):
    rate = models.IntegerField()
    projcet = models.ForeignKey(Project, on_delete=models.CASCADE)
    user = models.ForeignKey(Register, on_delete=models.CASCADE)

apps/home/views.py
# from asyncio.windows_events import NULL
from django import template
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.template import loader
from django.urls import reverse
from django.db.models import Avg, Sum
from collections import defaultdict
from datetime import datetime
import re
from apps.home.models import Category, Comment, Donation, Project, Image, Project_Report, Rate, Reply, Tag, Comment_Report
from apps.home.forms import Project_Form, Report_form, Reply_form, Category_form
from django.forms.utils import ErrorList
from apps.authentication.models import Register
NULL={}

def getUser(request):
        user = Register.objects.get(id=request.session['user_id'])
        return user
    
def index(request):
    if 'user_id' in request.session:
        user = getUser(request)
    else:
        user = None  # NULL should be replaced with None in Python

    highest_rated_projects = Project.objects.annotate(
       avg_rate=Avg('rate__rate')).order_by('-avg_rate')[:5]
    last_5_projects = Project.objects.all().order_by('-id')[:5]
    featured_projects = Project.objects.filter(is_featured=1)[:5]

    images = []
    for project in highest_rated_projects:
        image = project.image_set.all().first()  # Get the first image related to the project
        if image:  # Check if there is an image
            images.append(image.images.url)  # Add the image URL to the list
        else:
            images.append(None)  # You can append a default image URL here if needed

    context = {
        'highest_rated_projects': highest_rated_projects,
        'latest_5_projects': last_5_projects,
        'featured_projects': featured_projects,
        'images': images,
        'projects_count': len(Project.objects.all()),
        'donors_count': len(Donation.objects.all()),
        'reviews_count': len(Rate.objects.all()),
        'user': user
    }
    
    html_template = loader.get_template('home/index.html')
    return HttpResponse(html_template.render(context, request))
 
def create_new_project(request):
    if 'user_id' not in request.session:
        user = NULL
        return redirect('login')
    else:
        user = getUser(request)
        my_images = Image.objects.all()
        if request.method == 'GET':

            form = Project_Form()
           
            
            return render(request, "home/create-project.html", context={"form": form, 'images': my_images, "user":user})

        if request.method == "POST":
            tag_error=''
                    
            if "tag" in request.POST or request.POST['newTag']!="":
                
                if(request.POST['newTag']!= ''):

                    newTag=re.sub("\s+","_",request.POST['newTag'].strip())
                    new_tag=Tag.objects.create(name=newTag).id
                    request.POST = request.POST.copy()
                    request.POST.update({
	                "tag":new_tag
                    })
            else:
                tag_error="Please add tag"
            
                    
            form = Project_Form(request.POST, request.FILES)
            if tag_error!="":
                
               form.add_error('tag',tag_error)
               
            images = request.FILES.getlist('images')
            if form.is_valid():
                project = form.save(commit=False)
                project.user = user
                project.save()
                form.save_m2m()
                for image in images:
                    Image.objects.create(project_id=project.id, images=image)
                return redirect('home')
        else:
            form = Project_Form()
        return render(request, "home/create-project.html", context={"form": form, "user":user})


def show_project_details(request, project_id):
    if 'user_id' not in request.session:
        user = NULL
    else:
        user = getUser(request)
    try:
        project = Project.objects.get(id=project_id)
        donate = project.donation_set.all().aggregate(Sum("donation"))
        donations_count = len(project.donation_set.all())
        comments = project.comment_set.all()
        replies = Reply.objects.all()
        project_images = project.image_set.all()
        counter=[]
        for image in project_images:
            counter.append("1")
        counter.pop()
        tags = project.tag.all()
        related_projects_tags = []
        for tag in tags:
            related_projects_tags.append(tag.project_set.all())

        related_projects = Project.objects.none().union(*related_projects_tags)[:4]
        related_projects_images = []
        for related_project in related_projects:
            related_projects_images.append(related_project.image_set.all().first().images.url)


        myFormat = "%Y-%m-%d %H:%M:%S"
        today = datetime.strptime(datetime.now().strftime(myFormat), myFormat)
        end_date = datetime.strptime(project.end_time.strftime(myFormat), myFormat)
        days_diff = (end_date-today).days
        
        new_report_form = Report_form()
        reply = Reply_form()

        donation_average = (donate["donation__sum"] if donate["donation__sum"] else 0)*100/project.total_target
        average_rating = project.rate_set.all().aggregate(Avg('rate'))['rate__avg']

        # return user rating if found
        user_rating = 0
        
        if 'user_id' in request.session:
            # prev_rating = Project.rate_set.get(user_id=user.id)
            prev_rating=[]

            if prev_rating:
                user_rating = prev_rating[0].rate

        if average_rating is None:
            average_rating = 0

        context = {
            'project': project,
            'donation': donate["donation__sum"] if donate["donation__sum"] else 0,
            'donations': donations_count,
            'days': days_diff,
            'comments': comments,
            'project_images': project_images,
            'replies': replies,
            'tags': tags,

            'report_form': new_report_form,
            'reply_form': reply,
            'related_projects': related_projects,
            'images': related_projects_images,
            
            'check_target': project.total_target*.25,
            'donation_average': donation_average,

            'rating': average_rating*20,
            'user_rating': user_rating,
            'rating_range': range(5, 0, -1),
            'average_rating': average_rating,
            
            'user':user,
            'counter':counter
            }

        return render(request, "home/project-details.html", context)
    except Project.DoesNotExist:
        html_template = loader.get_template('home/page-404.html')
        return HttpResponse(html_template.render(context, request))
 

def get_tag_projects(request, tag_id):
    if 'user_id' not in request.session:
        user = NULL
    else:
        user = getUser(request)
    context = {}
    try:
        tag = Tag.objects.get(id=tag_id)
        projects = tag.project_set.all()

        donations = []
        progress_values = []
        images = []
        for project in projects:
            donate = project.donation_set.all().aggregate(Sum("donation"))
            total_donation = donate["donation__sum"] if donate["donation__sum"] else 0
            
            progress_values.append(total_donation * 100/project.total_target)
            donations.append(total_donation)
            images.append(project.image_set.all().first().images.url)

        context = {
            'title': tag,
            'projects': projects,
            'images': images,
            'donations': donations,
            'progress_values': progress_values,
            'user':user
        }
        return render(request, "home/tag-projects.html", context)
    except Project.DoesNotExist:
        html_template = loader.get_template('home/page-404.html')
        return HttpResponse(html_template.render(context, request))


def get_category_projects(request, category_id):
    if 'user_id' not in request.session:
        user = NULL
    else:
        user = getUser(request)
    context = {}
    try:
        projects = Project.objects.filter(
            category_id=category_id).all()

        donations = []
        progress_values = []
        images = []
        for project in projects:
            donate = project.donation_set.all().aggregate(Sum("donation"))
            total_donation = donate["donation__sum"] if donate["donation__sum"] else 0
            progress_values.append(total_donation * 100/project.total_target)

            donations.append(total_donation)

            images.append(project.image_set.all().first().images.url)

        title = Category.objects.get(id=category_id)
        context = {
            'title': title,
            'projects': projects,
            'donations': donations,
            'images': images,
            'progress_values': progress_values,
            'user':user
        }
        return render(request, "home/category.html", context)
    except Project.DoesNotExist:
        html_template = loader.get_template('home/page-404.html')
        return HttpResponse(html_template.render(context, request))


def all_projects(request):
    if 'user_id' not in request.session:
        user = NULL
    else:
        user = getUser(request)
    context = {}
    try:
        projects = Project.objects.all()

        donations = []
        progress_values = []
        images = []
        for project in projects:
            donate = project.donation_set.all().aggregate(Sum("donation"))
            total_donation = donate["donation__sum"] if donate["donation__sum"] else 0
            progress_values.append(total_donation * 100/project.total_target)
            donations.append(total_donation)
            images.append(project.image_set.all().first().images.url)

apps/templates/home/all_projects.html
{% extends 'layouts/projects_template.html' %}

apps/templates/home/category.html
{% extends 'layouts/projects_template.html' %}

{% block project_type %}
Category :
{% endblock project_type %}

apps/templates/home/category_form.html
{% extends 'layouts/base.html' %} {% block title %} Forms {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} {% block body_class %}
forms-sections {% endblock body_class %} {% block content %}
{% comment %} {% include "includes/navigation-light.html" %} {% endcomment %}

<div class="container mt-5">
    <div class="row d-flex justify-content-center">

        <form method="post" action="category_form" class="card w-50 text-center mt-5" autocomplete="off">

            {%csrf_token%}
            {%for field in form%}
            <label for="">Category</label>
            <input type="text" name="{{field.name}}" />
            <span class="text-error">{{ form_error }}</span>
            {%endfor%}
            <button type="submit" class="btn bg-outline-danger"> save</button>
        </form>

    </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

<script src="/static/assets/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}

apps/templates/home/create-project.html
{% extends 'layouts/base.html' %}

{% block title %} Create Project {% endblock title %}

{% block content %}
<div class="container">
  <div class="py-5 mx-auto">
    <div class="col-md-8 card d-flex shadow-lg p-4 mt-5 mx-auto">
      <div class="text-center">
        <h3 class="text-gradient text-primary">Create New Project</h3>
      </div>
      <div class="card card-plain">
        <form role="form" id="contact-form" method="post" autocomplete="off" enctype="multipart/form-data">
          {% csrf_token %}

          <div class="mb-3">
            <label class="form-label">Project Title</label>
            {{ form.title }}
          </div>
          <span class="text-error">{{ form.title.errors }}</span>

          <div class="mb-3">
            <label class="form-label">Details</label>
            {{ form.details }}
          </div>
          <span class="text-error">{{ form.details.errors }}</span>

          <div class="mb-3">
            <label class="form-label">Total Target</label>
            {{ form.total_target }}
          </div>
          <span class="text-error">{{ form.total_target.errors }}</span>

          <div class="mb-3">
            <label class="form-label">Start Date & Time</label>
            {{ form.start_time }}
          </div>
          <span class="text-error">{{ form.start_time.errors }}</span>

          <div class="mb-3">
            <label class="form-label">End Date & Time</label>

            {{ form.end_time }}
          </div>
          <span class="text-error">{{ form.end_time.errors }}</span>

          <div class="mb-3">
            <label class="form-label">Category</label>

            {{ form.category }}
          </div>
          <span class="text-error">{{ form.category.errors }}</span>


          <div class="mb-3">
            <label class="form-label">Add tag</label>
            <input type="text" class="inp form-control my-1" maxlength="8" name="newTag" class="form-control"  id="id_tag"/>
            <span class="show_tag " style="padding: 2px;background-color: rgba(145, 9, 120, 0.61);border-radius: 15%; color: rgb(241, 240, 255);"></span>
            <p style="margin: 2px; color: black; font-size: small; font-weight: 550;">or choose one : </p>
            {{ form.tag }}
          </div>
          <span class="text-error">{{ form.tag.errors }}</span>

          <div class="mb-3">
            <label class="form-label">Photos</label><br />
            <input class="form-control" type="file" name="images" multiple required>
          </div>

          <div class="text-center">
            <button type="submit" name="create_project" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">
              Create
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<script>


// let btnAdd = document.querySelector('button');
let input = document.querySelector('.inp');
let show = document.querySelector('.show_tag');

input.addEventListener('keyup', () =>{
    show.innerText = input.value.replace(/\s+/g,'_').trim()

    
  
});
</script>
{% endblock content %}

apps/templates/home/index.html
{% extends 'layouts/base.html' %}
{% load index %}

{% block title %} Home Page {%endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}
<style>
  .featuredProject-image {
    display: flex;
    justify-content: flex-start;
    align-items: flex-end;
    background-position: center;
    background-repeat: no-repeat;
  }

  .featuredProject-image:after {
    position: absolute;
    top: 0;
    width: 100%;
    height: 100%;
    background-image: linear-gradient(rgba(0, 0, 0, 0.85), rgba(0, 0, 0, 0.85));
    content: "";
  }

  .carousel-caption {
    bottom: 45%;
  }

  .carousel-indicators {
    bottom: 20%;
  }

  #featured .card.card-background.card-background-mask-primary::after {
    background-image: linear-gradient(310deg, #8d0599 0%, #ed3d3d 100%);
  }
</style>
{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}


{% block content %}

<!-- slider -->

<header class="header-2">
  <div class="page-header section-height-75 relative">
    <div class="col-md-12 p-0">
      <div class="row">
        <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-bs-target="#myCarousel" data-bs-slide-to="0" class="active"></li>
            <li data-bs-target="#myCarousel" data-bs-slide-to="1"></li>
            <li data-bs-target="#myCarousel" data-bs-slide-to="2"></li>
            <li data-bs-target="#myCarousel" data-bs-slide-to="3"></li>
            <li data-bs-target="#myCarousel" data-bs-slide-to="4"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">

            {%for project in highest_rated_projects%}

            <div class="carousel-item {% if forloop.first %}active{%endif%}">
              <div class="featuredProject-image section-height-75 relative" style="
                        background-image: url('{{ images|index:forloop.counter0 }}');
                        background-size: cover;
                      "></div>
              <div class="carousel-caption d-none d-md-block">
                <a href="{% url 'show_project' project.id %}">
                  <h3 class="text-light font-weight-bolder">{{ project.title|title }}</h3>
                  <p class="w-75 mx-auto text-uppercase text-light">Click and start donating now</p>
                </a>
              </div>
            </div>

            {%endfor%}

          </div>

          <!-- Left and right controls -->
          <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
    </div>
    <div class="position-absolute w-100 z-index-1 bottom-0">
      <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
        viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
        <defs>
          <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
        </defs>
        <g class="moving-waves">
          <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
          <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
          <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
          <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
          <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
          <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95" />
        </g>
      </svg>
    </div>
  </div>
</header>

<!-- Counter -->
<section class="pt-3 pb-4" id="count-stats">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 z-index-2 border-radius-xl mt-n8 mx-auto py-3 blur shadow-blur">
        <div class="row">
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h3 class="text-gradient text-primary">
                <span id="state1" countTo="{{ donors_count }}"></span>+
              </h3>
              <h5 class="mt-3">Donors</h5>
              <p class="text-sm">
                People of different ages are welcome to donate
              </p>
            </div>
            <hr class="vertical dark" />
          </div>
          <div class="col-md-4 position-relative">
            <div class="p-3 text-center">
              <h3 class="text-gradient text-primary">
                <span id="state2" countTo="{{ projects_count }}"></span>+
              </h3>
              <h5 class="mt-3">Projects</h5>
              <p class="text-sm">Various Projects that deserve to be donated</p>
            </div>
            <hr class="vertical dark" />
          </div>
          <div class="col-md-4">
            <div class="p-3 text-center">
              <h3 class="text-gradient text-primary">
                <span id="state3" countTo="{{ reviews_count }}"></span>+
              </h3>
              <h5 class="mt-3">Reviews</h5>
              <p class="text-sm">Feel free to rate projects and give us a feedback</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- List Projects -->
<section class="my-5 py-5">
  <div class="container">
    <div class="row align-items-center">
      <!-- Latest Projects -->
      <div class="col-lg-6 ms-auto me-auto p-lg-2 mt-lg-0 mt-4">
        <div class="card card-background card-background-mask-primary tilt" data-tilt>
          <div class="full-background" style="
              background-image: url('https://images.unsplash.com/photo-1579389083395-4507e98b5e67?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=934&q=80');
            "></div>
          <div class="card-body pt-5 text-center">
            <h2 class="text-white up mb-4">
              <i class="fa-solid fa-list-check mx-3"></i>Latest Projects
            </h2>
            <ul class="text-left">
              {%for project in latest_5_projects%}
              <li>
                <a href="{% url 'show_project' project.id %}" class="text-light font-weight-bold">
                  {{ project.title|title }}
                </a>
              </li>
              {%empty%}
              <h5 class="text-light text-center">No Projects Found</h5>
              {%endfor%}
            </ul>
            <a href="{%url 'all_projects'%}" class="btn btn-outline-white mt-3 btn-round">View All</a>
          </div>
        </div>
      </div>

      <!-- Featured Projects -->
      <div id="featured" class="col-lg-6 ms-auto me-auto p-lg-2 mt-lg-0 mt-4">
        <div class="card card-background card-background-mask-primary tilt" data-tilt>
          <div class="full-background" style="
              background-image: url('../../static/assets/img/featured.jpg');
            "></div>
          <div class="card-body pt-5 text-center">
            <h2 class="text-white up mb-4">
              <i class="fa-solid fa-lightbulb mx-3"></i>Featured Projects
            </h2>
            <ul class="text-left">
              {%for project in featured_projects%}
              <li>
                <a href="{% url 'show_project' project.id %}" class="text-light font-weight-bold">
                  {{ project.title|title }}
                </a>
              </li>
              {%empty%}
              <h5 class="text-light text-center">No Featured Projects</h5>
              {%endfor%}
            </ul>
            </ul>
            <a href="{% url 'featured_projects' %}" class="btn btn-outline-white mt-3 btn-round">View All</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="py-3 mt-3">
  <div class="container">
    <div class="row justify-space-between text-center py-2">
      <div class="col-12 mx-auto">
        <a class="btn bg-gradient-primary w-auto me-2 p-3 text-light" href="{% url 'create_project'%}">Create your own
          <b>Project</b></a>
          
      </div>
    </div>
  </div>
</section>
{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}

<script src="/static/assets/js/plugins/countup.min.js"></script>
<script src="/static/assets/js/plugins/tilt.min.js"></script>

<!-- Counters Script -->
<script type="text/javascript">
  if (document.getElementById("state1")) {
    const countUp = new CountUp(
      "state1",
      document.getElementById("state1").getAttribute("countTo")
    );
    if (!countUp.error) {
      countUp.start();
    } else {
      console.error(countUp.error);
    }
  }
  if (document.getElementById("state2")) {
    const countUp1 = new CountUp(
      "state2",
      document.getElementById("state2").getAttribute("countTo")
    );
    if (!countUp1.error) {
      countUp1.start();
    } else {
      console.error(countUp1.error);
    }
  }
  if (document.getElementById("state3")) {
    const countUp2 = new CountUp(
      "state3",
      document.getElementById("state3").getAttribute("countTo")
    );
    if (!countUp2.error) {
      countUp2.start();
    } else {
      console.error(countUp2.error);
    }
  }
</script>

<script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.3.3/gsap.min.js"></script>
{% endblock javascripts %}

apps/templates/home/page-403.html
{% extends 'layouts/base.html' %}

{% block title %} Error 403 {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} contact-us {% endblock body_class %}

{% block content %}

  {% comment %} {% include "includes/navigation-light.html" %} {% endcomment %}

  <header>
    <div class="page-header section-height-85">
      <div>
        <img class="position-absolute fixed-top ms-auto w-50 h-100 z-index-0 d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 border-top-start-radius-0 border-bottom-end-radius-0" src="/static/assets/img/curved-images/curved8.jpg">
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 d-flex justify-content-center flex-column">
            <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="text-center">
                <h3 class="text-gradient text-primary">
                    Error 403
                </h3>
                <p class="mb-0">
                  Access denied. Please contact support or authenticate.
                </p>
              </div>
              <form role="form" id="contact-form" method="post" autocomplete="off">
                  <div class="row">
                    <div class="col-md-12 text-center">
                      <a href="/" class="btn bg-gradient-primary mt-3 mb-0">HOME</a>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script src="/static/assets/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>

{% endblock javascripts %}

apps/templates/home/search-result.html
{% extends 'layouts/projects_template.html' %}

{% load index %}

{% block project_type %}
Projects related to your search : <br />
{% endblock project_type %}

{% block extra_content_title %}
Tags related to your search : <br />
{% endblock extra_content_title %}